// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "git-register-project/internal/models"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockUserRegister is a mock of UserRegister interface.
type MockUserRegister struct {
	ctrl     *gomock.Controller
	recorder *MockUserRegisterMockRecorder
}

// MockUserRegisterMockRecorder is the mock recorder for MockUserRegister.
type MockUserRegisterMockRecorder struct {
	mock *MockUserRegister
}

// NewMockUserRegister creates a new mock instance.
func NewMockUserRegister(ctrl *gomock.Controller) *MockUserRegister {
	mock := &MockUserRegister{ctrl: ctrl}
	mock.recorder = &MockUserRegisterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRegister) EXPECT() *MockUserRegisterMockRecorder {
	return m.recorder
}

// CheckEmailExists mocks base method.
func (m *MockUserRegister) CheckEmailExists(email string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckEmailExists", email)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckEmailExists indicates an expected call of CheckEmailExists.
func (mr *MockUserRegisterMockRecorder) CheckEmailExists(email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckEmailExists", reflect.TypeOf((*MockUserRegister)(nil).CheckEmailExists), email)
}

// CreateUser mocks base method.
func (m *MockUserRegister) CreateUser(user *models.UserRedis) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserRegisterMockRecorder) CreateUser(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserRegister)(nil).CreateUser), user)
}

// MockEmailSender is a mock of EmailSender interface.
type MockEmailSender struct {
	ctrl     *gomock.Controller
	recorder *MockEmailSenderMockRecorder
}

// MockEmailSenderMockRecorder is the mock recorder for MockEmailSender.
type MockEmailSenderMockRecorder struct {
	mock *MockEmailSender
}

// NewMockEmailSender creates a new mock instance.
func NewMockEmailSender(ctrl *gomock.Controller) *MockEmailSender {
	mock := &MockEmailSender{ctrl: ctrl}
	mock.recorder = &MockEmailSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailSender) EXPECT() *MockEmailSenderMockRecorder {
	return m.recorder
}

// SendConfremRegister mocks base method.
func (m *MockEmailSender) SendConfremRegister(toEmail, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendConfremRegister", toEmail, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendConfremRegister indicates an expected call of SendConfremRegister.
func (mr *MockEmailSenderMockRecorder) SendConfremRegister(toEmail, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendConfremRegister", reflect.TypeOf((*MockEmailSender)(nil).SendConfremRegister), toEmail, code)
}

// MockRedisClient is a mock of RedisClient interface.
type MockRedisClient struct {
	ctrl     *gomock.Controller
	recorder *MockRedisClientMockRecorder
}

// MockRedisClientMockRecorder is the mock recorder for MockRedisClient.
type MockRedisClientMockRecorder struct {
	mock *MockRedisClient
}

// NewMockRedisClient creates a new mock instance.
func NewMockRedisClient(ctrl *gomock.Controller) *MockRedisClient {
	mock := &MockRedisClient{ctrl: ctrl}
	mock.recorder = &MockRedisClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedisClient) EXPECT() *MockRedisClientMockRecorder {
	return m.recorder
}

// Del mocks base method.
func (m *MockRedisClient) Del(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Del", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Del indicates an expected call of Del.
func (mr *MockRedisClientMockRecorder) Del(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Del", reflect.TypeOf((*MockRedisClient)(nil).Del), ctx, key)
}

// Get mocks base method.
func (m *MockRedisClient) Get(ctx context.Context, key string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRedisClientMockRecorder) Get(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRedisClient)(nil).Get), ctx, key)
}

// Set mocks base method.
func (m *MockRedisClient) Set(ctx context.Context, key string, value []byte, expiration time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, key, value, expiration)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockRedisClientMockRecorder) Set(ctx, key, value, expiration interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockRedisClient)(nil).Set), ctx, key, value, expiration)
}

// MockUserLogin is a mock of UserLogin interface.
type MockUserLogin struct {
	ctrl     *gomock.Controller
	recorder *MockUserLoginMockRecorder
}

// MockUserLoginMockRecorder is the mock recorder for MockUserLogin.
type MockUserLoginMockRecorder struct {
	mock *MockUserLogin
}

// NewMockUserLogin creates a new mock instance.
func NewMockUserLogin(ctrl *gomock.Controller) *MockUserLogin {
	mock := &MockUserLogin{ctrl: ctrl}
	mock.recorder = &MockUserLoginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserLogin) EXPECT() *MockUserLoginMockRecorder {
	return m.recorder
}

// InsertRefreshToken mocks base method.
func (m *MockUserLogin) InsertRefreshToken(userID int, refreshTokenHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertRefreshToken", userID, refreshTokenHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertRefreshToken indicates an expected call of InsertRefreshToken.
func (mr *MockUserLoginMockRecorder) InsertRefreshToken(userID, refreshTokenHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertRefreshToken", reflect.TypeOf((*MockUserLogin)(nil).InsertRefreshToken), userID, refreshTokenHash)
}

// SelectUser mocks base method.
func (m *MockUserLogin) SelectUser(ctx context.Context, email string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectUser", ctx, email)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectUser indicates an expected call of SelectUser.
func (mr *MockUserLoginMockRecorder) SelectUser(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectUser", reflect.TypeOf((*MockUserLogin)(nil).SelectUser), ctx, email)
}

// MockTokenGenerator is a mock of TokenGenerator interface.
type MockTokenGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockTokenGeneratorMockRecorder
}

// MockTokenGeneratorMockRecorder is the mock recorder for MockTokenGenerator.
type MockTokenGeneratorMockRecorder struct {
	mock *MockTokenGenerator
}

// NewMockTokenGenerator creates a new mock instance.
func NewMockTokenGenerator(ctrl *gomock.Controller) *MockTokenGenerator {
	mock := &MockTokenGenerator{ctrl: ctrl}
	mock.recorder = &MockTokenGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenGenerator) EXPECT() *MockTokenGeneratorMockRecorder {
	return m.recorder
}

// AccessJWT mocks base method.
func (m *MockTokenGenerator) AccessJWT(userID int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AccessJWT", userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AccessJWT indicates an expected call of AccessJWT.
func (mr *MockTokenGeneratorMockRecorder) AccessJWT(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccessJWT", reflect.TypeOf((*MockTokenGenerator)(nil).AccessJWT), userID)
}

// CheckHash mocks base method.
func (m *MockTokenGenerator) CheckHash(password, hash string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckHash", password, hash)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CheckHash indicates an expected call of CheckHash.
func (mr *MockTokenGeneratorMockRecorder) CheckHash(password, hash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckHash", reflect.TypeOf((*MockTokenGenerator)(nil).CheckHash), password, hash)
}

// HashRefreshToken mocks base method.
func (m *MockTokenGenerator) HashRefreshToken(token string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HashRefreshToken", token)
	ret0, _ := ret[0].(string)
	return ret0
}

// HashRefreshToken indicates an expected call of HashRefreshToken.
func (mr *MockTokenGeneratorMockRecorder) HashRefreshToken(token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HashRefreshToken", reflect.TypeOf((*MockTokenGenerator)(nil).HashRefreshToken), token)
}

// RefreshJWT mocks base method.
func (m *MockTokenGenerator) RefreshJWT(userID int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshJWT", userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshJWT indicates an expected call of RefreshJWT.
func (mr *MockTokenGeneratorMockRecorder) RefreshJWT(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshJWT", reflect.TypeOf((*MockTokenGenerator)(nil).RefreshJWT), userID)
}

// ValidateToken mocks base method.
func (m *MockTokenGenerator) ValidateToken(tokenStr string) (map[string]interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateToken", tokenStr)
	ret0, _ := ret[0].(map[string]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateToken indicates an expected call of ValidateToken.
func (mr *MockTokenGeneratorMockRecorder) ValidateToken(tokenStr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateToken", reflect.TypeOf((*MockTokenGenerator)(nil).ValidateToken), tokenStr)
}

// MockRefreshtoken is a mock of Refreshtoken interface.
type MockRefreshtoken struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshtokenMockRecorder
}

// MockRefreshtokenMockRecorder is the mock recorder for MockRefreshtoken.
type MockRefreshtokenMockRecorder struct {
	mock *MockRefreshtoken
}

// NewMockRefreshtoken creates a new mock instance.
func NewMockRefreshtoken(ctrl *gomock.Controller) *MockRefreshtoken {
	mock := &MockRefreshtoken{ctrl: ctrl}
	mock.recorder = &MockRefreshtokenMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshtoken) EXPECT() *MockRefreshtokenMockRecorder {
	return m.recorder
}

// SelectRefreshToken mocks base method.
func (m *MockRefreshtoken) SelectRefreshToken(ctx context.Context, id int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectRefreshToken", ctx, id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectRefreshToken indicates an expected call of SelectRefreshToken.
func (mr *MockRefreshtokenMockRecorder) SelectRefreshToken(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectRefreshToken", reflect.TypeOf((*MockRefreshtoken)(nil).SelectRefreshToken), ctx, id)
}

// UpdateRefreshToken mocks base method.
func (m *MockRefreshtoken) UpdateRefreshToken(ctx context.Context, id int, token string, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRefreshToken", ctx, id, token, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRefreshToken indicates an expected call of UpdateRefreshToken.
func (mr *MockRefreshtokenMockRecorder) UpdateRefreshToken(ctx, id, token, expiresAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRefreshToken", reflect.TypeOf((*MockRefreshtoken)(nil).UpdateRefreshToken), ctx, id, token, expiresAt)
}
